# --------------------- #
#    Generation File    #
# --------------------- #

# Other generation files to import. (Example: intensive_apps -> ~/.config/rebos/imports/intensive_apps.toml)
imports = [
  # "intensive_apps",
  "core",
]

pkg_managers.system.pkgs = [
  "aria2",
  "asciinema",
  "atuin",
  "bat",
  "bottom",
  "btop",
  "bless",
  "cava",
  "chezmoi",
  "cups",
  "detox",
  "difftastic",
  "direnv",
  "duf",
  "dust",
  "fd",
  "fish",
  "flatpak",
  "floorp",
  "fzf",
  "gdu",
  "git",
  "github-cli",
  "gparted",
  "grex",
  "gvfs",
  "hyperfine",
  "imagemagick",
  "jq",
  "kitty",
  "lazygit",
  "lolcat",
  "lsd",
  "lua51",
  "luarocks",
  "mdcat",
  "mosh",
  "mpv",
  "navi",
  "neofetch",
  "noto-fonts",
  "noto-fonts-emoji",
  "nvtop",
  "otf-font-awesome",
  "ouch",
  "peaclock",
  "progress",
  "prusa-slicer",
  "ripgrep",
  "skim",
  "speedtest-rs",
  "spotify-player-full-git",
  "spotifyd",
  "starship",
  "syncthing",
  "tealdeer",
  "thefuck",
  "thunar",
  "thunar-volman",
  "tumbler",
  "ffmpegthumbnailer",
  "thunar-archive-plugin",
  "timeshift",
  "timeshift-autosnap",
  "tokei",
  "topgrade",
  "trash-cli",
  "ttf-firacode-nerd",
  "ttf-jetbrains-mono",
  "ttf-jetbrains-mono-nerd",
  "ventoy",
  "vesktop",
  "wakatime",
  "wezterm-git",
  "wget",
  "wine",
  "wttrbar",
  "yazi",
  "youtube-dl-git",
  "youtube-dl-gui",
  "yt-dlp",
  "ytfzf",
  "zellij",
  "zoxide",
] # Packages to be installed via the native package manager.

# Packages to be installed via Flatpak.
pkg_managers.flatpak.pkgs = [
  "com.github.tchx84.Flatseal",
  "md.obsidian.Obsidian",
  "net.ankiweb.Anki",
]

# Packages to be installed via Cargo.
pkg_managers.cargo.pkgs = [
  "bacon",
  "bob-nvim",
  "cargo-binstall",
  "cargo-audit",
  "cargo-geiger",
  "cargo-nextest",
  "cargo-udeps",
  "cross",
  "cargo-cache",
  "cargo-bloat",
  "porsmo",
  "wthrr",
  "irust",
  "cargo-info",
  "wiki-tui",
  "mprocs",
  "uwuify",
]

pkg_managers.bob.pkgs = ["nightly"]

pkg_managers.luarocks.pkgs = ["magick --local --lua-version=5.1"]
