
add = "bob install #:?"  # Example for APT: 'sudo apt install #:?'
remove = "bob unadd #:?" # Example for APT: 'sudo apt remove #:?'
upgrade = "bob update --all" # Example for APT: 'sudo apt upgrade'

plural_name = "neovim" # Example for APT: 'system packages'


[config]
many_args = false
