# ----------------------------------- #
#    Package Manager Configuration    #
# ----------------------------------- #

# Make sure to enter the exact command you use as the normal user!
# That means including 'sudo' or 'doas' or whatever if the command needs it.
# Where you would put packages, enter '#:?'.

# Example: add = "sudo apt install #:?"

add = "paru -S #:?"   # Example: sudo apt install #:?
remove = "paru -Runs #:?" # Example: sudo apt remove #:?
sync = "paru -Syy"        # Example: sudo apt update
upgrade = "paru -Syyu"    # Example: sudo apt upgrade

plural_name = "system packages"

# ------------------------------- #
#    Additional configuration.    #
# ------------------------------- #

# many_pkg_args = BOOL: Can you supply many packages as an argument? Example: 'sudo apt add git vim wget'

[config]
many_args = true
