pkg_managers.system.pkgs = [
  "adobe-source-code-pro-fonts",
  "blueman",
  "bluez",
  "bluez-utils",
  "eog",
  "flatpak-xdg-utils",
  "gnome-system-monitor",
  "gtk-engine-murrine",
  "libnotify",
  "mousepad",
  "mpv-mpris",
  "network-manager-applet",
  "networkmanager",
  "notification-daemon",
  "noto-fonts-emoji",
  "otf-font-awesome",
  "python-pywal",
  "qt5ct",
  "qt6ct",
  "qt6-svg",
  "sox",
  "swappy",
  "ttf-droid",
  "ttf-fira-code",
  "ttf-jetbrains-mono",
  "ttf-jetbrains-mono-nerd",
  "waybar-updates",
  "wttrbar-git",
  "wireplumber",
  "xdg-desktop-portal",
  "xdg-desktop-portal-gtk",
  "xdg-user-dirs",
  "xdg-utils",
  "yad",
]
