[managers.system]
items  = [
  "cliphist",
  "waybar",
  "rofi-lbonn-wayland-git",
  "swww",
  "swaync",
  "nwg-look-bin",
  "qt5-wayland",
  "sddm",
  "grim",
  "slurp",
  "kvantum",
  "polkit-gnome",
  "wlogout",
]
