pkg_managers.system.pkgs = [
  "cliphist",
  # "waybar",
  "rofi-lbonn-wayland-git",
  "swww",
  "swaync",
  "nwg-look-bin",
  "hyprlock-git",
  "hypridle",
  "qt5-wayland",
  "sddm",
  "grim",
  "slurp",
  "kvantum",
  "polkit-gnome",
  "wlogout",
]
